#
# Copyright (C) 2024 Intel Corporation.
#
# SPDX-License-Identifier: Apache-2.0
#


 ## Current Developer Toolbox doesn't support environment files, make sure to remove any files or environment variables starting with $
version: '3.7'
networks:
  checkout-network:
    driver: bridge
services:
  camera-simulator:
    container_name: camera-simulator
    image: aler9/rtsp-simple-server
    ipc: "none"
    ports:
      - "8555:8554"
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    env_file:
      - .env
    networks:
      checkout-network: {}
  camera-simulator0:
    image: jrottenberg/ffmpeg:4.1-alpine
    container_name: camera-simulator0
    entrypoint: ["/bin/sh","-c"]
    command: 
    - | 
       if [ ! -f /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4 ]; then
          mkdir -p /home/pipeline-server/sample-media
          wget -O /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4 https://www.pexels.com/download/video/4465029
       fi
       ffmpeg -nostdin -re -stream_loop -1 -i /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://camera-simulator:8554/camera_0
    depends_on:
      - camera-simulator
    volumes:
      - ${RETAIL_USE_CASE_ROOT:-..}/performance-tools/sample-media:/home/pipeline-server/sample-media
    env_file:
      - .env
    networks:
      checkout-network: {}
  camera-simulator1:
    image: jrottenberg/ffmpeg:4.1-alpine
    container_name: camera-simulator1
    entrypoint: ["/bin/sh","-c"]
    command: 
    - | 
       if [ ! -f /home/pipeline-server/sample-media/barcode-1920-15-bench.mp4 ]; then
          mkdir -p /home/pipeline-server/sample-media
          wget -O /home/pipeline-server/sample-media/barcode-1920-15-bench.mp4 https://github.com/antoniomtz/sample-clips/raw/main/barcode.mp4
       fi
       ffmpeg -nostdin -re -stream_loop -1 -i /home/pipeline-server/sample-media/barcode-1920-15-bench.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://camera-simulator:8554/camera_1
    depends_on:
      - camera-simulator
    volumes:
      - ${RETAIL_USE_CASE_ROOT:-..}/performance-tools/sample-media:/home/pipeline-server/sample-media
    env_file:
      - .env
    networks:
      checkout-network: {}
  camera-simulator2:
    image: jrottenberg/ffmpeg:4.1-alpine
    container_name: camera-simulator2
    entrypoint: ["/bin/sh","-c"]
    command: 
    - | 
       if [ ! -f /home/pipeline-server/sample-media/vehicle-bike-1920-15-bench.mp4 ]; then
          mkdir -p /home/pipeline-server/sample-media
          wget -O /home/pipeline-server/sample-media/vehicle-bike-1920-15-bench.mp4 https://www.pexels.com/download/video/853908
       fi
       ffmpeg -nostdin -re -stream_loop -1 -i /home/pipeline-server/sample-media/vehicle-bike-1920-15-bench.mp4 -c copy -f rtsp -rtsp_transport tcp rtsp://camera-simulator:8554/camera_2
    depends_on:
      - camera-simulator
    volumes:
      - ${RETAIL_USE_CASE_ROOT:-..}/performance-tools/sample-media:/home/pipeline-server/sample-media
    env_file:
      - .env
    networks:
      checkout-network: {}

  evamclient:
    container_name: edge-video-analytics-microservice
    image: intel/edge-video-analytics-microservice:2.4.0
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy},${RTSP_CAMERA_IP}
      ENABLE_RTSP: true
      RTSP_PORT: 8554
      ENABLE_WEBRTC: true
      WEBRTC_SIGNALING_SERVER: http://${WHIP_SERVER_IP}:${WHIP_SERVER_PORT}
      RUN_MODE: EVA
      GENICAM: Balluff
      GST_DEBUG: 1,gencamsrc:2
      REST_SERVER_PORT: 8080
    env_file:
      - .env
    volumes:
      - ${RETAIL_USE_CASE_ROOT:-..}/src/extensions:/home/pipeline-server/gvapython
      - ${RETAIL_USE_CASE_ROOT:-../..}/models:/home/pipeline-server/models
      - ${RETAIL_USE_CASE_ROOT:-..}/src/pipeline-server/asc:/home/pipeline-server/pipelines
      - "${RETAIL_USE_CASE_ROOT:-..}/src/pipeline-server/config.json:/home/pipeline-server/config.json"
      - "/run/udev:/run/udev:ro"
      - "/dev:/dev"
      - "/tmp:/tmp"
      - vol_pipeline_root:/var/cache/pipeline_root:uid=1999,gid=1999
    network_mode: host    
    tty: true
    entrypoint: ["./run.sh"]
    group_add:
      - "109"
      - "110"
    devices:
      - "/dev:/dev"

  pipeline-init:
    image: postman/newman
    container_name: pipeline-init
    command: run /postman/pipeline.json -e "/postman/env.json" --verbose
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
    env_file:
      - .env
    volumes:
      - ./postman/:/postman
    network_mode: host

  mqtt-broker:
    command:
      - /usr/sbin/mosquitto
      - -c
      - /mosquitto-no-auth.conf
    container_name: mqtt-broker
    hostname: mqtt-broker
    image: eclipse-mosquitto:2.0.18
    ports:
      - mode: ingress
        host_ip: 127.0.0.1
        target: 1883
        published: "1883"
        protocol: tcp
    read_only: true
    restart: always
    security_opt:
      - no-new-privileges:true
    user: 2002:2001
    networks:
      checkout-network: {}

  mediamtx:
    image: bluenviron/mediamtx:1.11.3
    container_name: mediamtx-server
    environment:
      - MTX_LOGLEVEL=info
      - MTX_RTSP=no
      - MTX_RTMP=no
      - MTX_SRT=no
      - MTX_RTMP=no
      - MTX_HLS=no
      - MTX_SRT=no
      - MTX_WEBRTCADDRESS=:${WHIP_SERVER_PORT}
    network_mode: host

volumes:
  vol_pipeline_root:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
