version: '3.7'

services:
  camera-simulator:
    image: aler9/rtsp-simple-server
    ports:
      - "8554:8554"
    networks:
      - overlaynet

  camera-simulator0:
    image: openvino/ubuntu20_data_runtime:2021.4.2
    container_name: camera-simulator0
    entrypoint: ffmpeg
    command: >
        -nostdin
        -re -stream_loop -1
        -i /home/pipeline-server/sample-media/coca-cola-4465029-1920-15-bench.mp4
        -c copy
        -f rtsp
        -rtsp_transport tcp
        rtsp://camera-simulator:8554/camera_0
    depends_on:
      - camera-simulator
    volumes:
      - ${RETAIL_USE_CASE_ROOT:-..}/performance-tools/sample-media:/home/pipeline-server/sample-media
    networks:
      - overlaynet

  OvmsClientGst:
    image: dlstreamer:dev
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - camera-simulator0
    entrypoint: /script/entrypoint.sh --pipeline_script_choice ${PIPELINE_SCRIPT:-yolov5s.sh}
    networks:
      - overlaynet
    env_file:
      - ./res/gst.env
      - ${DEVICE_ENV:-res/all-cpu.env}
    environment:
      - INPUTSRC=${INPUTSRC:-rtsp://camera-simulator:8554/camera_0}
      - CONTAINER_NAME="gst0"            
    volumes:
      - ${RESULTS_DIR:-../results}:/tmp/results
      - ./res/:/home/pipeline-server/envs
      - ${RETAIL_USE_CASE_ROOT:-..}/models:/home/pipeline-server/models
networks:
  overlaynet:
    driver: overlay
